name: shelf_code_generator_example
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  meta: ^1.16.0

  # Model utils
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Code generation
  source_gen: ^1.4.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  analyzer: ^6.8.0
  build: ^2.4.1

dev_dependencies:
  http: ^1.1.0
  lints: ^4.0.0
  test: ^1.24.0

  # Model Utils
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  # Code generation
  build_runner: ^2.4.6
